### PR TITLE
Fix issue 137: added `Transform.CurrentRawRecord()` for caller of omniparser to access the raw ingested record.

### LINKED ISSUE #137: Return unique hash for input
So i'm busy ingesting shipments, they arrive as either csv, json, xml or edi

The interface I'm working should take an array of shipments, divide that into individual shipments, hash those and store the original input for success/audit/retry/failure tracking reasons. This would make it easier to ingest 99/100 shipments and retry (after localizing and fixing the issue) that one shipment that's invalid for whatever reason.

In order to decide whether something has been ingested correctly I thought a solution could be hashing it 'unit' of input and storing the original input somewhere as well

Quite easy for csv

Weird python-and-bash-esque psuedocode:
```
for line in csv:
  process(line) && hash(line) && gzip(line) -> store result, hash, line in db
```
  
 It becomes less so for json and xml, even marshal and unmarshal is not 100% identical to the input
 
 Even worse is EDI
 
 So, even though I liked the idea of storing the _original_ it quickly becomse cumbersome. A decent alternative is is hashing and storing the output of transform.Read()
 
 But that comes with several issues
 - I can change the output and thus the hash using the schema (not really an issue)
 - its not original (but it is more consistent (all json)), so kind of bug/feature
 - I don't see what I haven't told omniparser to see, so new fields that might have been added
 
 None of these are a major issue, but part of hashing a new representation of the input, not the input itself
 
 I was wondering how hard would it be to hash the input of whatever generates the output would be?
 So:
 hash, data, err := transform.Read
 
 Is your internal data stable enough? That you could say 'for loop' the IDR input through the sha256 encoder (it supports streaming) and return a stable/unchanging hash?

As in, in theory ["a", "b", "c"] should return the same hash for a, b and c regardless of ordering

Also, I imagine being able to verify whether a file has been fully processed is interesting for more than one usecase

### PR DESCRIPTION
**Pull request by jf-tech**
Fix #137

### CODE REVIEW

**Comment by jf-tech** [comment]
FYI @DGollings

**Comment by DGollings** [comment]
Cool, thanks. Two remarks:

1.
Maybe instead of returning interface{} return say 

```
type RawRecorder interface {
  UUIDv3() // (or Checksum() if you want to be more schema agnostic)
}
```

That way a user can get useful output without any casts or RTFM, if they want more they can always cast to actual type.

2.
I kind of liked the output of 
```
            "hash_json_input": { "custom_func": {
                "name": "javascript_with_context",
                "args": [ { "const": "_node" } ]
            }},
```

Seeing that say SG25/SG26/position had value "1" is much clearer than the concatenated fieldless output of rawRecord.Node.InnerText()

Had a look around, none of the simpel options (json.marshal and Sprintf("%+v") resulted in similar output. Could probably generate similar output by walking the tree but that's non-trivial code. Was wondering if you had a better solution.

Although this is not really an issue, I already store a checksum of the entire schema, so if `schemaChecksum == storedChecksum && rawRecordChecksum == storedRecordChecksum` I can safely assume that the schema can be used to debug an original input file. Even without knowing the exact input.
And in a sense, that's better, I can feed the transformed output to a retry function (fixing import errors), I can't feed {""SG25/SG26/position" : "1"} to anything. Well, not without making changes

For context, say fixing an incomplete address for delivery purposes.

rawRecord.UUIDv3() + transformed output is probably better, I just kind of liked how hash_json_input/_node looked :)

**Comment by jf-tech** [comment]
1) given we have vastly different implementation of schema handlers across different versions I don't want to force any constraints (e.g. an interface) onto what each schema handler want to define as a raw record. It's highly version specific. So no.

2) you can use `idr.JSONify2(*idr.Node)` to marshal an IDR tree into a mimified JSON blob. That's how `javascript_with_context` does it.

**Comment by DGollings** [comment]
1. but it wouldn't enforce anything regarding implementation, constraints or definition of a raw record in any way? The only thing it would enforce would be the existence of a function called Hash() or Checksum(), which returns a string, and that string could be "not implemented"
2. thanks :)

**Comment by jf-tech** [comment]
After some thinking, I agree with 1, PR coming.

**Pull request merged**
